#!/usr/bin/env bash
# config_edit by Mr Green [mrgreen@archbang.org]
# Edit Openbox Window Manager and reconfigure.

editor="l3afpad"

path="$HOME/.config/openbox"

options="Menu\nConfig\nAutostart\nReload"

chosen=$(echo -e "$options" | rofi -p 'Select Option' -dmenu )

case $chosen in
	"Menu")  ${editor} ${path}/menu.xml ;;

	"Config") ${editor} ${path}/rc.xml ;;

	"Autostart") ${editor} ${path}/autostart ;;

	"Reload") openbox --reconfigure ;;
esac

