#!/usr/bin/env bash
# abpost_install script
# created by mrgreen [mrgreen@archbang.org]
#
# check network, mirrors, create keys, updates system
# installs yay aur helper

# Check for a network connection
ping -c 1 archlinux.org > /dev/null 2>&1 || { echo "Network is not reachable. Check your connection and try again." >&2; exit 1; }

# Check if mirrorlist backup file is present, if not run abserver.
[ -f "/etc/pacman.d/mirrorlist.abbackup" ] || abserver 

# Initialize and populate pacman keyring, update system, and install dependencies
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -Syu archlinux-keyring git base-devel --needed --noconfirm

# install yay
echo "Installing yay..."
git clone https://aur.archlinux.org/yay.git /tmp/yay
cd /tmp/yay || exit
makepkg -si --noconfirm
cd - || exit
rm -rf /tmp/yay
sudo pacman -R --noconfirm go
echo -e "\nYay Aur helper now installed..."


