#!/usr/bin/env bash
# exitmenu by Mr Green [mrgreen@archbang.org]
# Power Options for ArchBang-sway 

options="Log Out\nReboot\nPoweroff"

chosen=$(echo -e "$options" | wofi -p 'Select Option' --dmenu )

case $chosen in
	"Log Out") i3 exit ;;

	"Reboot") reboot ;;

	"Poweroff") poweroff ;;
esac

