#!/bin/bash
# sway key binds for rofi
# poorly written by Mr Green [mrgreen@archbang.org]

gen_binds() { cat ~/.config/sway/config | grep bindsym | sed 's/\$//g;0,/term/s/term/foot/;s/exec//g;s/bindsym//g;s/mod/Super/g;/^#/d' ; }

echo empty; gen_binds | wofi --dmenu -p "Sway Keyboard Shortcuts"

