ipc_socket = true

[colors]

[colors.bright]
black = "#3d3a3a"
blue = "#8fa7b9"
cyan = "#6ec2a8"
green = "#8fb676"
magenta = "#bd89de"
red = "#d28abf"
white = "#dad3d3"
yellow = "#c8bc45"

[colors.cursor]
cursor = "#ffffff"
text = "#000000"

[colors.normal]
black = "#1c1c1c"
blue = "#77b6c5"
cyan = "#7fcab3"
green = "#9acc79"
magenta = "#a488d9"
red = "#d770af"
white = "#8d8d8d"
yellow = "#d0d26b"

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[font]
size = 9

[font.bold]
family = "monospace"

[font.bold_italic]
family = "monospace"

[font.italic]
family = "monospace"

[font.normal]
family = "monospace"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"
mods = "Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "G"
mods = "Control"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mode = "~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "C"
mode = "Vi|~Search"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "PasteSelection"
key = "Insert"
mods = "Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Control"

[scrolling]
history = 5000
multiplier = 3

[shell]
program = "/usr/bin/bash"

[window]
decorations = "full"
dynamic_title = false
title = "ArchBang Rules...."

[window.padding]
x = 10
y = 10
